---
- name: Get systemd version
  ansible.utils.cli_parse:
    command: systemd --version
    parser:
      name: ansible.netcommon.native
      template_path: "{{ role_path }}/templates/systemd_version_cli_parse.yaml"
    set_fact: systemd_version

- name: Install gosu
  package:
    name: gosu
    state: present

- name: Check for docker
  command: docker --version
  changed_when: false

- name: Install main bash script
  template:
    src: speedtest_cronjob.bash.j2
    dest: /usr/local/bin/speedtest_cronjob.bash
    owner: root
    group: root
    mode: 0755
- name: Install result uploader script
  copy:
    src: speedtest2pg.py
    dest: /usr/local/bin/speedtest2pg.py
    owner: root
    group: root
    mode: 0755

# Don't expose the password in the DBURI
- name: Install env vars file
  template:
    src: speedtest_env.j2
    dest: /etc/default/speedtest
    owner: root
    group: root
    mode: 0600
    backup: true

- name: Check systemd version vs vars
  assert:
    that: systemd_version['major'] | int >= 247 or not speedtest_fixed_random_delay
    fail_msg: >-
      FixedRandomDelay is not supported by systemd before version 247.
      Current version: {{ systemd_version['major'] }} ({{ systemd_version['full'] }})

- name: Install systemd service
  template:
    src: speedtest.service.j2
    dest: /etc/systemd/system/speedtest.service
  notify: Daemon-reload systemd
- name: Install systemd timer
  template:
    src: speedtest.timer.j2
    dest: /etc/systemd/system/speedtest.timer
  notify: Daemon-reload systemd
- meta: flush_handlers
- name: Enable and start systemd timer
  systemd:
    name: speedtest.timer
    state: started
    enabled: true
...
