---
- name: Install gosu
  package:
    name: gosu
    state: present

- name: Check for docker
  command: docker --version
  changed_when: false

- name: Install main bash script
  template:
    src: speedtest_cronjob.bash.j2
    dest: /usr/local/bin/speedtest_cronjob.bash
    owner: root
    group: root
    mode: 0755
- name: Install result uploader script
  copy:
    src: speedtest2pg.py
    dest: /usr/local/bin/speedtest2pg.py
    owner: root
    group: root
    mode: 0755

# TODO: can build this from ansible (vault/lookup)
- name: Check env vars file
  file:
    path: /etc/default/speedtest
    owner: root
    group: root
    mode: 0600
    state: file

- name: Install systemd service
  template:
    src: speedtest.service.j2
    dest: /etc/systemd/system/speedtest.service
  notify: Daemon-reload systemd
- name: Install systemd timer
  template:
    src: speedtest.timer.j2
    dest: /etc/systemd/system/speedtest.timer
  notify: Daemon-reload systemd
- meta: flush_handlers
- name: Enable and start systemd timer
  systemd:
    name: speedtest.timer
    state: started
    enabled: true
...
